### PR TITLE
Try to fix CI

### PR DESCRIPTION
**Pull request by terabyte25**
Yep, CI works now. Yay.

### CODE REVIEW

**Comment by terabyte25** [comment]
While not related to the discussion at hand, the GitLab repository isn't properly taking in any commits from here.

**Comment by psi29a** [comment]
I don't think mirroring is happening yet...

**Comment by terabyte25** [comment]
@psi29a yep, looks like the CI is working again.

**Comment by psi29a** [comment]
Cheers!

**Comment by psi29a** [comment]
Now... we need to look into gathering up the artifacts.

**Comment by terabyte25** [comment]
@psi29a yeah, but thing is it'll probably take 5 hours just to compile one single package for all architectures (if we compile all dependencies from scratch). And considering Travis CI has a timeout of 30 minutes, I don't really think it'll be possible.

Unless there's some brave soul out there wanting to make a nightly daily.

**Comment by psi29a** [comment]
Gitlab... we can use a docker container

**Comment by terabyte25** [comment]
Can't we use prebuilt dependencies to cut down on compile time? Not like we have to recompile them Everytime.

**Comment by psi29a** [comment]
Yeah, travis-ci and gitlab both allow for caching

**Pull request merged**
