### PR TITLE
Add russian keyboard support

### PR DESCRIPTION
**Pull request by terabyte25**
Just adds a small option to switch between English and Russian keyboards.

### CODE REVIEW

**Comment by psi29a** [comment]
Would be nice if we could get travis-ci working again...

**Comment by terabyte25** [comment]
Err, just to make sure, did I get the most common Russian layout?

**Comment by Capostrophic** [comment]
Nope.

**Comment by terabyte25** [comment]
@Capostrophic what's a good layout to use, then?

**Comment by terabyte25** [comment]
Hmm, the arrow button coordinates need to be changed a bit

**Comment by terabyte25** [comment]
Layout should be fixed now.

**Comment by terabyte25** [comment]
This PR is way to messy, will fix.

**Comment by psi29a** [comment]
woohoo, after latest merge... two test failures! :)  Perhaps best solution is fix this on xyzz's fork.. or... have him develop directly here. :D

**Comment by terabyte25** [comment]
@psi29a I'll make a PR in a bit *again*.

**Comment by psi29a** [comment]
Thank you. :)

Since xyzz isn't actively working on this fork... perhaps you should close this PR and open one against xyzz? I think he is better to determine about whether this is a good/necessary fix or not.

**Comment by terabyte25** [comment]
Yeah, and I do have a better way of implementing it instead of what I've done in this PR.

**Pull request closed without merging**
