### PR TITLE
Switch to gl4es

### PR DESCRIPTION
**Pull request by xyzz**
Turns out, using a wrapper and OSG in GL1 mode works way better than
GLESv1 without a wrapper.

Specifically, fixes the problem where textures are randomly flipped
on adreno.

### CODE REVIEW

**Comment by psi29a** [comment]
So back to using a wrapper? (glshim fork)

**Comment by xyzz** [comment]
Yep - works way better. Performance looked about the same to me.

It should be glesv1 compatible in theory but I got these random issues I spent a few days debugging and still didn't really get anywhere.

Having openmw be compatible with modern opengl (shaders instead of fixed pipeline) glesv2/3 would be really nice but it's a way bigger task.

**Comment by psi29a** [comment]
OK, merging.  Does the OSG fork need to be updated or not?

**Comment by xyzz** [comment]
Yep, https://github.com/OpenMW/osg/pull/10 especially the GL1 ifdef thing.

**Pull request merged**
