### PR TITLE
Fix CI again

### PR DESCRIPTION
**Pull request by terabyte25**

### CODE REVIEW

**Comment by terabyte25** [comment]
Took me *only* 12 commits.

**Comment by psi29a** [comment]
Will this also be sent as a patch/PR to xyzz?
That way we don't have breakage during next merge?

**Comment by terabyte25** [comment]
@psi29a I was hoping xyzz would fetch changes from upstream, but if he doesn't I suppose I'll have to make a PR for him.

**Comment by psi29a** [comment]
What would be ideal is that xyzz works on this exclusively (he has R/W access) or sometimes pushes to this fork.  

Please make a PR for him, or I will (reverse PR).

**Pull request merged**
