### PR TITLE
Updates, cleanups, build system rewrites, lots of everything

### PR DESCRIPTION
**Pull request by xyzz**
There are still issues but I think it's in a mergeable state now so that others can iterate on it.
(Btw, can somebody make `master` the main branch on this repo? I don't have any access)

In current state, you can start the game and walk out of the ship into the office at which point broken input makes it impossible to continue :(

https://forum.openmw.org/viewtopic.php?f=6&t=4894

Known issues:
* some textures are flipped, not sure if device-specific - I'm trying to debug it
* problems with input, e.g. no mouse cursor, text entry issues

High-level overview of current changes:
* I rewrote the build system so that it's really easy to build even for people without any android dev experience (as well, it should be easy to put up on travis - I'm just not sure if I should put travis into this repo or into the main openmw repo)
* Also switched toolchain to latest Google NDK instead of crystax - crystax is really outdated now (latest release about 2 years old)
* Cleaned up the project, removing old Eclipse files, etc; also removed `resource` folder which contained outdated resources - it's now copied over by the build system
* Just as a side note, it's using GLESv1, there's no gl1 wrapper.

Requires both https://github.com/OpenMW/openmw/pull/1599 and https://github.com/OpenMW/osg/pull/10

### CODE REVIEW

**Comment by psi29a** [comment]
It seems that there is currently no Master branch. WTF?

I'm doing cleanup for this repo. Since you're doing most of the development work here, I'll add you as an admin. :)

**Comment by psi29a** [comment]
BTW, I love the PR and the comments on why you made the PR. Keep up the good work!

**Comment by psi29a** [comment]
Sidenote: Since we are not using a glwrapper, and OpenMW seems to work with GLESv1, then this has implications beyond Android. :)

**Comment by psi29a** [comment]
Created Master branch from  alternative_controls, set it to protected.

**Comment by psi29a** [comment]
Will we eventually see some CI? To test all our your code-changes?

**Comment by xyzz** [comment]
About CI: I'm thinking about making two travis configs, one in this repo will build only the Java part on commit/pull-request normally + the cronjob will build everything and deploy the apk (somewhere?); another in the main openmw repo would only build libopenmw.so but not the Java part - I'd need to write a script to prebuild a prefix with all libs compiled so that it doesn't take ages on travis.

**Comment by psi29a** [comment]
That's a great idea on both sides. I didn't realize that this repo used a lib of openmw, but it makes sense.

Is there anything can be automated by using android-cmake instead making our own scripts?

**Pull request merged**
